### ISSUE TITLE
计划支持更多平台吗？

### ISSUE THREAD

**Issue by SiZapPaaiGwat** [artipub/artipub#5]

**Comment by yxw007** [comment]
是的，下一步会支持发布至微信公众号。请问是否有更多的想法和建议？😊

**Comment by yxw007** [comment]
> > 是的，下一步会支持发布至微信公众号。请问是否有更多的想法和建议？😊
> 
> 
> 
> 我的想法是发布到更多的海外平台和 CMS 系统：
> 
> 
> 
> - WordPress
> 
> - Blogger
> 
> - Ghost
> 
> - Hashnode
> 
> - Strapi
> 
> - Sanity
> 
> - Directus
> 
> - Hackernews
> 
> - Reddit
> 
> 

喔，想法很不错。 要不要来贡献添加几个平台插件呀 😆

其实前些天我看了一下国内主流平台：掘金、知乎等 都没有开放API，这就让人挺头痛的， 支持国内平台发布的是模拟登陆，这种集成方式我不是很喜欢，因为接口很可能会变，一下就导致用户无法使用了。 国外的大平台就好不少，只要有开放api 咋们的库就可以支持上。 你发的这么多平台，流量如何有了解吗？ 我的想法是优先把流行的平台插件补充上。 最近在思考实现一个翻译库，支持自动翻译文章然后发布文章，这样让用户更爽了。

**Comment by yxw007** [comment]
> 可以忽略国内用户，专注海外平台。付费意愿高。发自我的 iPhone在 2024年7月19日，13:06，Potter ***@***.***> 写道：﻿ 是的，下一步会支持发布至微信公众号。请问是否有更多的想法和建议？😊 我的想法是发布到更多的海外平台和 CMS 系统： WordPress Blogger Ghost Hashnode Strapi Sanity Directus Hackernews Reddit 喔，想法很不错。 要不要来贡献添加几个平台插件呀 😆 其实前些天我看了一下国内主流平台：掘金、知乎等 都没有开放API，这就让人挺头痛的， 支持国内平台发布的是模拟登陆，这种集成方式我不是很喜欢，因为接口很可能会变，一下就导致用户无法使用了。 国外的大平台就好不少，只要有开放api 咋们的库就可以支持上。 你发的这么多平台，流量如何有了解吗？ 我的想法是优先把流行的平台插件补充上。 最近在思考实现一个翻译库，支持自动翻译文章然后发布文章，这样让用户更爽了。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

嗯，国内付费意愿却是很低

**Comment by yxw007** [comment]
> 还有你现在这种方式不太适合做成产品，最好提供SaaS服务或者客户端。
非常赞同，这个库只是做产品的一个底层库，后面可能会考虑做一个产品网站

**Comment by yxw007** [comment]
> 还有你现在这种方式不太适合做成产品，最好提供SaaS服务或者客户端。

感谢你的建议，如果你有更多的建议欢迎加我微信沟通
https://yanxuewen.cn/about.html

**Comment by yxw007** [comment]
以后有问题在Discussions里面讨论
